apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- cert-manager-package-install.yaml
- contour-package-install.yaml
- redis.yaml
spec:
  dependsOn:
    - name: ./pre-reqs
secretGenerator:
- name: contour-packages-values
  namespace: packages
  files:
  - contour.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: contour-packages
- name: redis-packages-values
  namespace: packages
  files:
  - redis-values.yaml
  type: Opaque

