apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- contour-package-install.yaml
- cert-manager-package-install.yaml
spec:                       ## Added to test dependencies
  dependsOn:                ## Added to test dependencies
    - name: ./pre-reqs      ## Added to test dependencies
secretGenerator:
- name: contour-packages-values
  namespace: packages
  files:
  - contour.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: contour-packages