---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-namespaces
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: dependencybranch-tanzu-packages-cd            # Must match the name of the GitRepo you added in TMC
    namespace: tanzu-continuousdelivery-resources


